ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'MFA_CHALLENGE';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'UPDATE_TRIAGE';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'BACKUP_STRATEGY';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'SAFE_DOWNLOADS';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'APP_PERMISSION_AUDIT';
